export const CONFIG = {
  gravity: -38,
  risingGravityScale: 0.88,
  fallingGravityScale: 1.32,
  gravityTransitionSpeed: 8,
  walkSpeed: 9.4,
  groundAcceleration: 42,
  groundDeceleration: 46,
  groundProbeDistance: 1.34,
  jumpSpeed: 14,
  airAcceleration: 13.5,
  maxAirSpeed: 71,

  ropeMaxRange: 115,
  ropeMinLength: 7,
  ropePullSpeed: 17,
  ropePullMaxSpeed: 36,
  ropeSpring: 58,
  ropeDamping: 8,
  ropeReelAcceleration: 7.2,
  ropeReelMaxAcceleration: 27,
  ropeReelRadialForce: 24,
  ropeReleaseBoost: 6.8,
  ropeReleaseLift: 2.55,
  ropeFireDuration: 0.085,

  shotRange: 165,
  bombCount: 12,
  bombRespawnDelay: 1.25,
  bombChainRadius: 13,
  citySpacing: 28,
  cityHalfExtent: 6,
} as const;
